EAudit/Controllers/APIs/LookupController.cs
using EAudit.Controllers.Modules;
using EAudit.DAO;
using EAudit.DAO.Authentication;
using EAudit.DAO.LookUp;
using EAudit.Models;
using EAudit.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;

namespace EAudit.Controllers.APIs
{
    [Route("api/configuration/[controller]")]
    [ApiController]
    public class LookupController : ControllerBase
    {
        private readonly IAuthInterface _authRepository;
        private readonly ILookUp _lookupRepository;

        public LookupController(ILookUp lookupRepository, IAuthInterface authRepository)
        {
            _authRepository = authRepository;
            _lookupRepository = lookupRepository;
        }


        [HttpPost]
        [Route("standar_spmi")]
        public async Task<IActionResult> StandarSPMI_List([FromBody] DataTableFilter filter)
        {
            List<LookUp_Standar_SPMI> result = await _lookupRepository.getStandarSPMI_List(filter.search);
            var json = System.Text.Json.JsonSerializer.Serialize(result);
            return Ok(json);
        }

        public async Task<IActionResult> StandarSPMIImport(IFormFile file)
        {
            var list = new List<LookUp_Standar_SPMI>();
            using(var stream=new MemoryStream())
            {
                await file.CopyToAsync(stream);
                using(var package= new ExcelPackage(stream))
                {
                    ExcelWorksheet worksheet = package.Workbook.Worksheets[0];
                    var rowcount = worksheet.Dimension.Rows;
                    for (int row=2;row<=rowcount;row++)
                    {
                        var no_standar = worksheet.Cells[row, 1].Value.ToString().Trim();
                       
                        var data_import = new LookUp_Standar_SPMI
                        {
                            NOSTANDAR = no_standar,
                            PERNYATAAN = worksheet.Cells[row, 2].Value.ToString().Trim(),
                            INDIKATOR = worksheet.Cells[row, 3].Value.ToString().Trim(),
                        };

                        List<LookUp_Standar_SPMI> result = await _lookupRepository.getStandarSPMI_ListByNoStandar(no_standar);
                        if (result.Count > 0)
                        {
                            data_import.ID = result[0].ID;
                        }
                        _lookupRepository.StandarSPMI_Save(data_import);
                        list.Add(data_import);

                    }
                }
            }
            return RedirectToAction("index", "StandarSPMI");
        }

    
        [HttpPost]
        [Route("standar_spmi/save")]
        public IActionResult StandarSPMI_Save([FromBody] LookUp_Standar_SPMI data)
        {
            AjaxResponse response = new AjaxResponse();
            try
            {
                _lookupRepository.StandarSPMI_Save(data);
                response.result = "ok";
                response.message = "Standar SPMI Berhasil Disimpan.";
            }
            catch (Exception e)
            {
                response.result = "error";
                response.message = e.Message;
            }

            return Ok(response);
        }

        [HttpPost]
        [Route("standar_spmi/delete")]
        public IActionResult StandarSPMI_Delete([FromBody] LookUp_Standar_SPMI data)
        {
            AjaxResponse response = new AjaxResponse();
            try
            {
                _lookupRepository.StandarSPMI_Delete(data);
                response.result = "ok";
                response.message = "Standar SPMI Berhasil Dihapus.";
            }
            catch (Exception e)
            {
                response.result = "ok";
                response.message = e.Message;
            }

            return Ok(response);
        }

        [HttpPost]
        [Route("standar_spmi/delete_all")]
        public IActionResult StandarSPMI_DeleteAll()
        {
            AjaxResponse response = new AjaxResponse();
            try
            {
                _lookupRepository.StandarSpmiDeleteAll();
                response.result = "ok";
                response.message = "Semua Standar SPMI Berhasil Dihapus.";
            }
            catch (Exception e)
            {
                response.result = "ok";
                response.message = e.Message;
            }

            return Ok(response);
        }

    }
}

EAudit/Views/LookUp/standar_spmi_index.cshtml
@{
    ViewData["placeHolderFilter"] = "Pencarian berdasarkan No Standar/Pernyataan/Indikator";
}

<partial name="~/Views/Shared/_PageHeaderTitle.cshtml" />

<div class="content">
    <div class="container-fluid">

        <partial view-data="ViewData" name="~/Views/Shared/Filter/Filter_2Field.cshtml" />

        <div class="row">
            <div class="col-md-12">
                <div class="card card-default card-sm">

                    <div class="card-body card-body-sm">
                        <table class="table table-bordered table-striped table-responsive-sm" style="width:100%" id="gridStandarSPMI">
                            <thead>
                                <tr>
                                    <th>NO</th>
                                    <th>NO STANDAR</th>
                                    <th>PERNYATAAN</th>
                                    <th>INDIKATOR</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<partial name="~/Views/LookUp/standar_spmi_modal.cshtml" />

@section JavaScript
{
<script type="text/javascript">

</script>
<script type="text/javascript" src="@Url.Content("/js/modules/standar_spmi.js")"></script>

@*<script type="text/javascript" src="@Url.Content("/js/modules/auditee_edit.js")"></script>*@
}

EAudit/Views/LookUp/standar_spmi_modal.cshtml
<div class="modal fade" role="dialog" id="modalStandarSPMI" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalHeader">Default Modal</h4>
            </div>
             <form class="form-horizontal" method="post" role="form" id="formTambah">
            <div class="modal-body">
               
                    @Html.AntiForgeryToken()

                    <div class="form-group row form-group-sm">
                        <label for="txtNoStandar" class="col-sm-3 col-form-label col-form-label-sm">No Standar</label>
                        <div class="col-sm-9">
                            <input type="hidden" name="txtId" class="form-control form-control-sm" id="txtId">
                            <input type="text" name="txtNoStandar" class="form-control form-control-sm" id="txtNoStandar"
                                   placeholder="No Standar" required>
                        </div>
                    </div>

                    <div class="form-group row form-group-sm">
                        <label for="txtPernyataan" class="col-sm-3 col-form-label col-form-label-sm">Pernyataan Standar</label>
                        <div class="col-sm-9">
                            <textarea name="txtPernyataan" class="form-control form-control-sm" id="txtPernyataan"
                                   placeholder="Pernyataan" required></textarea>
                        </div>
                    </div>

                    <div class="form-group row form-group-sm">
                        <label for="txtIndikator" class="col-sm-3 col-form-label col-form-label-sm">Indikator Kerja</label>
                        <div class="col-sm-9">
                            <textarea name="txtIndikator" class="form-control form-control-sm" id="txtIndikator"
                                   placeholder="Indikator" required></textarea>
                        </div>
                    </div>

            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-success btn-sm">Simpan</button>
                <button type="button" id="btnCancel" class="btn btn-default btn-sm">Batal</button>
            </div>
            
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>

<div class="modal fade" role="dialog" id="modalImport" data-keyboard="false">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="modalHeader">Default Modal</h4>
            </div>
            <form class="form-horizontal" method="post" asp-controller="Lookup" asp-action="StandarSPMIImport" enctype="multipart/form-data">
            <div class="modal-body">
               
                    @Html.AntiForgeryToken()
                    <div class="form-group row form-group-sm">
                        <label for="txtNoStandar" class="col-sm-3 col-form-label col-form-label-sm">File Contoh</label>
                        <div class="col-sm-9 pt-2">
                             <a href="~/file_excel/file_contoh_standar_spmi.xlsx" id="btnCancel" class="btn btn-primary btn-sm">Unduh File Contoh</a>
                        </div>
                    </div>
                    <div class="form-group row form-group-sm">
                        <label for="txtNoStandar" class="col-sm-3 col-form-label col-form-label-sm">Upload Excel</label>
                        <div class="col-sm-9 pt-2">
                            <input type="file" name="file" accept="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel" required />
                        </div>
                    </div>

            </div>

            <div class="modal-footer">
                <button type="submit" class="btn btn-success btn-sm">Proses</button>
                <button type="button" id="btnCancel" class="btn btn-default btn-sm">Batal</button>
            </div>
            
            </form>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
@section JavaScript
{

}